version: '2.1'

services:
  # Test composition that runs on devices marked for testing
  sut:
    build: ./sut
    privileged: true
    restart: "no"
    depends_on:
      - "audio"
    volumes:
      - 'pulse:/run/pulse'
