version: '2.1'

services:
  # Test composition that runs on devices marked for testing
  sut:
    build: ./sut
    privileged: true
    restart: "no"
    network_mode: host
    depends_on:
      - "browser"
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)'
    labels:
      io.balena.features.supervisor-api: 1
      
