---
name: bCat Prototype

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

env:
  BALENA_CLI_URL: https://github.com/balena-io/balena-cli/releases/download
  BALENA_CLI_VERSION: 13.1.11
  DEBUG: 0
  DEVICE_TYPE: raspberrypi4-64
  FLEET: gh_vipulgupta2048/bcat-proto
  ENVIRONMENT: balena-cloud.com
  FLEET: balena/balena-cloud
  REGISTRY_USER: balenaci
  RELEASES: 50
  RETRY: 3
  SOCAT_VERSION: 1.7.4.2
  TEST_DEVICE_TYPE: qemux86-64
  VERBOSE: "false"

jobs:
  balenaCloud automated testing:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install additional dependencies
        id: extra-dependencies
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
        run: |
          set -ue
          if ! [[ "$(${RUNNER_TEMP}/balena-cli/balena version)" =~ "${BALENA_CLI_VERSION}" ]]; then
              release_zip="balena-cli-v${BALENA_CLI_VERSION}-linux-x64-standalone.zip"
              wget -q "${BALENA_CLI_URL}/v${BALENA_CLI_VERSION}/${release_zip}" \
                && unzip -q "${release_zip}" -d "${RUNNER_TEMP}" \
                && rm "${release_zip}"
          fi
          "${RUNNER_TEMP}/balena-cli/balena" version


      - name: produce docker-compose
        id: generate-compose
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
        runs: yq '. *= load("docker-compose.test.yml")' docker-compose.yml

      - name: push draft or finalise release
        id: push-release
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_API_KEY_PUSH }}
          cache: false
          environment: ${{ env.ENVIRONMENT }}
          fleet: bcat-proto
          github_token: ${{ secrets.GITHUB_TOKEN }}
          versionbot: true

      - name: check fleet for DUT devices
        id: check-DUT-devices
        run: |

# We need to this next step as many times as there are DUT devices in the fleet, so figure out a matrix type execution


     # https://github.com/balena-io/balena-cli/issues/1543
      - name: pin DUT devices to draft release
        id: pin-device
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
        run: |
          set -uae

          [[ '${{ env.VERBOSE }}' =~ on|On|Yes|yes|true|True ]] && set -x

          balena login --token '${{ secrets.BALENA_API_KEY_TEST }}'

          balena_releases="$(mktemp)"
          balena releases '${{ env.FLEET }}' | tail -n +2 | head -n ${{ env.RELEASES }} > "${balena_releases}"

          # convert to JSON to find the correct draft release id and commit
          release_id="$(while IFS=' ' read -r id commit created_at status semver is_final
          do
            printf '{"id":%s,"commit":"%s","created_at":"%s","status":"%s","semver":"%s","is_final":%s}\n' \
              "${id}" "${commit}" "${created_at}" "${status}" "${semver}" "${is_final}"
          done < "${balena_releases}" | jq -s | jq -r '.[] | select((.id==${{ steps.push-release.outputs.release_id }}) and (.is_final==false) and (.status=="success")).id')"

          commit="$(while IFS=' ' read -r id commit created_at status semver is_final
          do
            printf '{"id":%s,"commit":"%s","created_at":"%s","status":"%s","semver":"%s","is_final":%s}\n' \
              "${id}" "${commit}" "${created_at}" "${status}" "${semver}" "${is_final}"
          done < "${balena_releases}" | jq -s | jq -r '.[] | select(.id==${{ steps.push-release.outputs.release_id }}).commit')"

          if ! [ '${{ steps.register-test-device.outputs.balena_device_id }}' = '' ] \
            && ! [ "${release_id}" = '' ] \
            && ! [ "${commit}" = '' ]; then
              # pin DUT to draft release
              curl -X PATCH --silent --retry ${{ env.RETRY }} --fail -o /dev/null \
                'https://api.${{ env.ENVIRONMENT }}/v6/device?$filter=id%20in%20(${{ steps.register-test-device.outputs.balena_device_id }})' \
                -H 'authorization: Bearer ${{ secrets.BALENA_API_KEY_TEST }}' \
                -H 'content-type: application/json' \
                --data-raw "{\"should_be_running__release\":${release_id}}" \
                --compressed
          fi

          balena device ${{ steps.check-DUT-devices.outputs.balena_device_uuid }}

          app_id="$(balena fleet ${{ env.FLEET }} | grep ^ID: | cut -c14-)"

          echo "::set-output name=balena_app_id::${app_id}"

      # (TBC) additional overrides for testing (i.e. DB_USER, DB_PASSWORD, etc.)

<<<<<<< Updated upstream
      - name: FIND IF THE CONTAINER HAS EXITED with which EXIT code 
        id: generate-compose
        if: github.event_name === 'pull_request'
        runs: OUR DOCKER COMPOSE GENERATOR
      
      - name: MARK THE RELEASE WITH EXIT CODE 
        id: generate-compose
        if: github.event_name === 'pull_request'
        runs: OUR DOCKER COMPOSE GENERATOR
      
      - name: PASS/FAIL the release 
        id: generate-compose
        if: github.event_name === 'pull_request'
        runs: OUR DOCKER COMPOSE GENERATOR
      
=======
      # - name: FIND IF THE CONTAINER HAS EXITED with which EXIT code
      #   id: generate-compose
      #   if: github.event_name === 'pull_request'
      #   runs: OUR DOCKER COMPOSE GENERATOR

      # - name: MARK THE RELEASE WITH EXIT CODE
      #   id: generate-compose
      #   if: github.event_name === 'pull_request'
      #   runs: OUR DOCKER COMPOSE GENERATOR

      # - name: PASS/FAIL the release
      #   id: generate-compose
      #   if: github.event_name === 'pull_request'
      #   runs: OUR DOCKER COMPOSE GENERATOR
>>>>>>> Stashed changes
