---
name: bCat Prototype

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

env:
  BALENA_CLI_URL: https://github.com/balena-io/balena-cli/releases/download
  BALENA_CLI_VERSION: 13.1.11
  DEVICE_TYPE: raspberrypi4-64
  FLEET: gh_vipulgupta2048/bcat-proto
  ENVIRONMENT: balena-cloud.com
  RELEASES: 50
  RETRY: 3
  TEST_DEVICE_TYPE: qemux86-64
  VERBOSE: "false"

jobs:
  balena-automated-testing:
    strategy:
      fail-fast: true
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install additional dependencies
        id: extra-dependencies
        run: |
          set -ue
          if ! [[ "$(${RUNNER_TEMP}/balena-cli/balena version)" =~ "${BALENA_CLI_VERSION}" ]]; then
              release_zip="balena-cli-v${BALENA_CLI_VERSION}-linux-x64-standalone.zip"
              wget -q "${BALENA_CLI_URL}/v${BALENA_CLI_VERSION}/${release_zip}" \
                && unzip -q "${release_zip}" -d "${RUNNER_TEMP}" \
                && rm "${release_zip}"
          fi
          "${RUNNER_TEMP}/balena-cli/balena" version
          grep -q "${RUNNER_TEMP}/balena-cli" "${GITHUB_PATH}" \
            || echo "${RUNNER_TEMP}/balena-cli" >> "${GITHUB_PATH}"

      - name: produce docker-compose
        id: generate-compose
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
        run: yq '. *= load("docker-compose.test.yml")' docker-compose.yml

      - name: push draft or finalise release
        id: push-release
        uses: balena-io/deploy-to-balena-action@v0.10.7
        with:
          balena_token: ${{ secrets.BALENACLOUD_API_KEY }}
          environment: ${{ env.ENVIRONMENT }}
          fleet: ${{ env.FLEET }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: find DUT device
        id: find-test-device
        run: |
          set -uae

          [[ '${{ env.VERBOSE }}' =~ on|On|Yes|yes|true|True ]] && set -x

          balena login --token '${{ secrets.BALENACLOUD_API_KEY }}'

          app_id="$(balena fleet ${{ env.FLEET }} | grep ^ID: | cut -c14-)"
          echo "::set-output name=balena_app_id::${app_id}"

          dut_id=$(curl --silent --retry ${{ env.RETRY }} --fail -o /dev/null \
            'https://api.${{ env.ENVIRONMENT }}/v6/device?$top=1&$select=id&$filter=belongs_to__application%20eq%20(${app_id})%20and%20device_tag/any(dt:dt/tag_key%20eq%20%27dut:${{ env.DEVICE_TYPE }}%27)' \
            -H 'authorization: Bearer ${{ secrets.BALENACLOUD_API_KEY }}' \
            -H 'content-type: application/json' \
            | jq -r '.d[].id')
          echo "::set-output name=balena_dut_id::${dut_id}"

     # https://github.com/balena-io/balena-cli/issues/1543
      - name: pin DUT devices to draft release
        id: pin-device
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
        run: |
          set -uae

          [[ '${{ env.VERBOSE }}' =~ on|On|Yes|yes|true|True ]] && set -x

          balena login --token '${{ secrets.BALENACLOUD_API_KEY }}'

          balena_releases="$(mktemp)"
          balena releases '${{ env.FLEET }}' | tail -n +2 | head -n ${{ env.RELEASES }} > "${balena_releases}"

          # convert to JSON to find the correct draft release id and commit
          release_id="$(while IFS=' ' read -r id commit created_at status semver is_final
          do
            printf '{"id":%s,"commit":"%s","created_at":"%s","status":"%s","semver":"%s","is_final":%s}\n' \
              "${id}" "${commit}" "${created_at}" "${status}" "${semver}" "${is_final}"
          done < "${balena_releases}" | jq -s | jq -r '.[] | select((.id==${{ steps.push-release.outputs.release_id }}) and (.is_final==false) and (.status=="success")).id')"

          commit="$(while IFS=' ' read -r id commit created_at status semver is_final
          do
            printf '{"id":%s,"commit":"%s","created_at":"%s","status":"%s","semver":"%s","is_final":%s}\n' \
              "${id}" "${commit}" "${created_at}" "${status}" "${semver}" "${is_final}"
          done < "${balena_releases}" | jq -s | jq -r '.[] | select(.id==${{ steps.push-release.outputs.release_id }}).commit')"

          if ! [ '${{ steps.find-test-device.outputs.balena_dut_id }}' = '' ] \
            && ! [ "${release_id}" = '' ] \
            && ! [ "${commit}" = '' ]; then
              # pin DUT to draft release
              curl -X PATCH --silent --retry ${{ env.RETRY }} --fail -o /dev/null \
                'https://api.${{ env.ENVIRONMENT }}/v6/device?$filter=id%20in%20(${{ steps.find-test-device.outputs.balena_dut_id }})' \
                -H 'authorization: Bearer ${{ secrets.BALENACLOUD_API_KEY }}' \
                -H 'content-type: application/json' \
                --data-raw "{\"should_be_running__release\":${release_id}}" \
                --compressed
          fi

      # (TBC) additional overrides for testing (i.e. DB_USER, DB_PASSWORD, etc.)

      # - name: FIND IF THE CONTAINER HAS EXITED with which EXIT code
      #   id: generate-compose
      #   if: github.event_name === 'pull_request'
      #   run: OUR DOCKER COMPOSE GENERATOR

      # - name: MARK THE RELEASE WITH EXIT CODE
      #   id: generate-compose
      #   if: github.event_name === 'pull_request'
      #   run: OUR DOCKER COMPOSE GENERATOR

      # - name: PASS/FAIL the release
      #   id: generate-compose
      #   if: github.event_name === 'pull_request'
      #   run: OUR DOCKER COMPOSE GENERATOR
